sonar.projectKey=Freensh_notesy
sonar.organization=freensh
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/static/**,**/staticfiles/**,**/migrations/**,**/.sessions/**
sonar.python.version=3.12
sonar.qualitygate.wait=true
